defaults: &base
  host: <%= ENV['REDIS_HOST'] || '127.0.0.1' %>
  port: <%= ENV['REDIS_PORT'] || '6379' %>
  url: <%= ENV['REDIS_URL'] %>

development:
  <<: *base
test:
  <<: *base
production:
  <<: *base
